postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-353-storm-or-magneto-3839a16
vote:
  image:
    tag: SA-353-storm-or-magneto-3839a16
worker:
  image:
    tag: updating-cb26ce0
