postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-335-wolverine-or-magneto-4232629
vote:
  image:
    tag: SA-335-wolverine-or-magneto-4232629
worker:
  image:
    tag: updating-cb26ce0
