postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-347-wolverine-or-mojo-618aed9
vote:
  image:
    tag: SA-346-gambit-or-magneto-bfaa8c1
worker:
  image:
    tag: updating-cb26ce0
