postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-184-jubilee-or-mojo-f921756
vote:
  image:
    tag: SA-184-jubilee-or-mojo-f921756
worker:
  image:
    tag: updating-cb26ce0
