postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-282-rogue-or-mystique-818bb9f
vote:
  image:
    tag: SA-282-rogue-or-mystique-818bb9f
worker:
  image:
    tag: updating-cb26ce0
