postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-196-beast-or-toad-6aa0675
vote:
  image:
    tag: SA-196-beast-or-toad-6aa0675
worker:
  image:
    tag: updating-cb26ce0
