postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-283-rogue-or-magneto-7273252
vote:
  image:
    tag: SA-283-rogue-or-magneto-7273252
worker:
  image:
    tag: updating-cb26ce0
