postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-267-storm-or-mystique-c697fb0
vote:
  image:
    tag: SA-267-storm-or-mystique-c697fb0
worker:
  image:
    tag: updating-cb26ce0
