postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-312-cyclops-or-juggernaut-c6b1ffc
vote:
  image:
    tag: SA-312-cyclops-or-juggernaut-c6b1ffc
worker:
  image:
    tag: updating-cb26ce0
