postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-350-jubilee-or-juggernaut-dcbdbfd
vote:
  image:
    tag: SA-350-jubilee-or-juggernaut-dcbdbfd
worker:
  image:
    tag: updating-cb26ce0
