postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-366-beast-or-mojo-3ceec96
vote:
  image:
    tag: SA-366-beast-or-mojo-3ceec96
worker:
  image:
    tag: updating-cb26ce0
