postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-228-jubilee-or-magneto-33bc89a
vote:
  image:
    tag: SA-228-jubilee-or-magneto-33bc89a
worker:
  image:
    tag: updating-cb26ce0
