postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-221-beast-or-pyro-0295972
vote:
  image:
    tag: SA-220-storm-or-mystique-3e5b415
worker:
  image:
    tag: updating-cb26ce0
