postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-177-wolverine-or-magneto-b0d766d
vote:
  image:
    tag: SA-173-cyclops-or-toad-e6d81ac
worker:
  image:
    tag: updating-cb26ce0
