postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-257-wolverine-or-toad-af2478f
vote:
  image:
    tag: SA-256-gambit-or-mojo-9595c48
worker:
  image:
    tag: updating-cb26ce0
