postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-339-jubilee-or-toad-a0b5b25
vote:
  image:
    tag: SA-339-jubilee-or-toad-a0b5b25
worker:
  image:
    tag: updating-cb26ce0
