postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-205-jubilee-or-sabretooth-410055d
vote:
  image:
    tag: SA-204-jubilee-or-magneto-4feb9c7
worker:
  image:
    tag: updating-cb26ce0
