postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-271-wolverine-or-toad-373f384
vote:
  image:
    tag: SA-270-rogue-or-pyro-ca89c24
worker:
  image:
    tag: updating-cb26ce0
