postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-315-beast-or-magneto-2544a3f
vote:
  image:
    tag: SA-315-beast-or-magneto-2544a3f
worker:
  image:
    tag: updating-cb26ce0
